package com.scarlatti.certloader.ui.controls;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.scarlatti.certloader.ui.UIComponent;
import com.scarlatti.certloader.ui.model.Cert;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * ______    __                         __           ____             __     __  __  _
 * ___/ _ | / /__ ___ ___ ___ ____  ___/ /______    / __/______ _____/ /__ _/ /_/ /_(_)
 * __/ __ |/ / -_|_-<(_-</ _ `/ _ \/ _  / __/ _ \  _\ \/ __/ _ `/ __/ / _ `/ __/ __/ /
 * /_/ |_/_/\__/___/___/\_,_/_//_/\_,_/_/  \___/ /___/\__/\_,_/_/ /_/\_,_/\__/\__/_/
 * Saturday, 2/10/2018
 */
public class CertListWrapper implements UIComponent {
    private JPanel jPanel;
    private CertListLoadingProgress progressBar;
    private CertLoadingError errorMessage;
    private CertList certList;
    private WelcomeMessage welcomeMessage;
    private CardLayout layout;

    public CertListWrapper() {
        layout = (CardLayout) jPanel.getLayout();
        layout.show(jPanel, "welcomeMessage");
    }

    public void welcome() {
        layout.show(jPanel, "welcomeMessage");
    }

    /**
     * Display the progress bar.
     * Utilize callbacks to alert when progress complete.
     */
    public void loading(Runnable onTimeout) {
        layout.show(jPanel, "progressBar");

        progressBar.load(10000, onTimeout);
    }

    public void stopLoading() {
        progressBar.stop();
    }

    /**
     * Select certs to install.
     */
    public void listCerts(String url, List<Cert> certs, CertList.InstallCallback installCallback) {
        certList.init(url, certs, installCallback);
        layout.show(jPanel, "certList");
    }

    public void error(String url, Exception e) {
        layout.show(jPanel, "errorMessage");
        errorMessage.init("Error Connecting to <" + url + ">", e);
    }

    @Override
    public JPanel getJPanel() {
        return jPanel;
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new CardLayout(0, 0));
        jPanel.setMinimumSize(new Dimension(-1, -1));
        jPanel.setOpaque(false);
        jPanel.setPreferredSize(new Dimension(-1, -1));
        jPanel.setRequestFocusEnabled(false);
        errorMessage = new CertLoadingError();
        jPanel.add(errorMessage.$$$getRootComponent$$$(), "errorMessage");
        certList = new CertList();
        jPanel.add(certList.$$$getRootComponent$$$(), "certList");
        welcomeMessage = new WelcomeMessage();
        jPanel.add(welcomeMessage.$$$getRootComponent$$$(), "welcomeMessage");
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        jPanel.add(panel1, "progressBar");
        progressBar = new CertListLoadingProgress();
        panel1.add(progressBar.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
