package com.scarlatti.certloader.ui.controls;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.scarlatti.certloader.ui.UIComponent;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 * ______    __                         __           ____             __     __  __  _
 * ___/ _ | / /__ ___ ___ ___ ____  ___/ /______    / __/______ _____/ /__ _/ /_/ /_(_)
 * __/ __ |/ / -_|_-<(_-</ _ `/ _ \/ _  / __/ _ \  _\ \/ __/ _ `/ __/ / _ `/ __/ __/ /
 * /_/ |_/_/\__/___/___/\_,_/_//_/\_,_/_/  \___/ /___/\__/\_,_/_/ /_/\_,_/\__/\__/_/
 * Saturday, 2/10/2018
 */
public class URLToolbar implements UIComponent {
    private JTextField url;
    private JButton downloadButton;
    private JPanel jPanel;

    private boolean loading = false;
    private AbstractLoadAction loadAction = noOpLoadAction();

    public URLToolbar() {
        setupListeners();
    }

    private void setupListeners() {
        downloadButton.addActionListener(this::doStartDownload);
        url.addActionListener(this::doStartDownload);
    }

    private void doStartDownload(ActionEvent e) {
        if (loading) {
            cancel();
        } else {
            load();
        }
    }

    public URLToolbar(AbstractLoadAction loadAction) {
        this.loadAction = loadAction;
    }

    public void load() {
        setLoading(true);

        new Thread(() -> {
            // ... and do the loading stuff here...
            loadAction.load(url.getText(), () -> {
                setLoading(false);
            }, () -> {
                setLoading(false);
            });
        }).start();
    }

    public void cancel() {

        // ... and do the canceling here...
        loadAction.cancel(() -> {
            setLoading(false);
        });
    }

    public void setLoading(boolean loading) {
        this.loading = loading;

        if (loading) {
            loadingMode();
        } else {
            resetMode();
        }
    }

    private void loadingMode() {
        url.setEnabled(false);
        downloadButton.setText("Cancel");
    }

    private void resetMode() {
        url.setEnabled(true);
        downloadButton.setText("Download Certificate(s)");
    }

    @Override
    public JPanel getJPanel() {
        return jPanel;
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel = new JPanel();
        jPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        jPanel.setEnabled(true);
        jPanel.setOpaque(true);
        jPanel.setPreferredSize(new Dimension(1280, 56));
        jPanel.setRequestFocusEnabled(false);
        final JLabel label1 = new JLabel();
        label1.setText("URL:");
        jPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        url = new JTextField();
        jPanel.add(url, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        downloadButton = new JButton();
        downloadButton.setText("Download Certificate(s)");
        jPanel.add(downloadButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }

    public static abstract class AbstractLoadAction {
        public abstract void load(String url, ActionCompletedCallback callback, ActionCompletedCallback errorCallback);

        public abstract void cancel(ActionCompletedCallback callback);

        @FunctionalInterface
        public interface ActionCompletedCallback {
            void callback();
        }
    }

    public static AbstractLoadAction noOpLoadAction() {
        return new AbstractLoadAction() {
            @Override
            public void load(String url, ActionCompletedCallback callback, ActionCompletedCallback errorCallback) {
                new Thread(() -> {
                    try {
                        Thread.sleep(4000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    callback.callback();
                }).start();
            }

            @Override
            public void cancel(ActionCompletedCallback callback) {
                new Thread(() -> {
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    callback.callback();
                }).start();
            }
        };
    }

    public AbstractLoadAction getLoadAction() {
        return loadAction;
    }

    public void setLoadAction(AbstractLoadAction loadAction) {
        this.loadAction = loadAction;
    }
}
